version: "3"

services:
    finxi-challenge:
        build: '.'
        image: finxi-challenge-image
        container_name: finxi-challenge
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
